name: update_index

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+*'
    branches:
      - master
      - main

jobs:
  Send-file-to-index:
    runs-on: ubuntu-latest
    steps:

    - name: Pushes test file
      uses: ow-gryphon/update-grypy-action@main
      env:
        API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
      with:
        repository_name: ${{ github.event.repository.name }}
        user_email: 'vittorfpereira@gmail.com'
        user_name: 'vittorfp'
        github_context: ${{ toJson(github) }}
#        commit_message: 'Adding metadata for the template ${{github.repository}}.'
